### ISSUE TITLE
Event Emission on selecting the start-date and end-date

### ISSUE THREAD

**Issue by anish000kumar** [Artistan/vuejs-range-datepickers#1]
Currently the documentation doesn't mention anything about events emitted on choosing dates. Are there any events to use?

**Comment by Artistan** [comment]
There is standard input emission and a submit-callback.

**Comment by Artistan** [comment]
https://vuejs.org/v2/guide/components.html

> So for a component to work with v-model, it should (these can be configured in 2.2.0+):
accept a value prop
emit an input event with the new value
