### ISSUE TITLE
Module not found: Error: Can't resolve './DateUtils.js' in '/app/1f85ef6b-c403-4945-97d3-082c151cc65d'

### ISSUE THREAD

**Issue by Mouvedia** [Artistan/vuejs-range-datepickers#2]

**Comment by Artistan** [comment]
where is this?

**Comment by Artistan** [comment]
DateUtils.js is part of the vuejs-datepicker package which mine extends.

**Comment by Mouvedia** [comment]
> where is this?

https://www.webpackbin.com/bins/-KpBRW5ApXMKlUxne80q

**Comment by Artistan** [comment]
updated the bin.
thanks.

**Comment by Mouvedia** [comment]
@Artistan you have to update the README with the new URL.

**Comment by Artistan** [comment]
webpackbin.com is a bit odd. if you click between pages it works, sometime, ... 🙄

**Comment by Artistan** [comment]
is working for me now. had to manually add the classes that the datepicker.vue 
I will try to let webpackbin people know that there is an issue with including npm modules that have other included classes 👍
